### ISSUE TITLE
🚀 Feature: Add package-lock.json for npm

### ISSUE THREAD

**Issue by seriouslysean** [philly-js-club/philly-js-club-website#12]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/philly-js-club/philly-js-club-website-remix/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Use `npm ci` rather than `pnpm i`.

### Additional Info

I typically use `npm` instead of `pnpm`. I don't know of any reason, conflicts or otherwise, that it shouldn't be added as `pnpm` doesn't need it. Figured it wouldn't hurt to ask.

**Comment by GV14982** [comment]
I don't think that's a particularly good idea. PNPM and NPM have different methods for resolving packages and mixing package managers can cause inconsistent issues that would differ from machine to machine.

**Comment by seriouslysean** [comment]
Works for me, I’ll just use it as-is. Thanks for the explanation.
