### ISSUE TITLE
🛠 Tooling: Remove compliance action PR title checks?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [philly-js-club/philly-js-club-website#14]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/philly-js-club/philly-js-club-website-remix/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Nobody other than me has been using semantic PR titles (`chore: ...`, `feat: ...`, etc.). And because this repo doesn't have semantic-versioned releases (`1.2.3`, etc.), there's really not much _technical_ benefit to using them... Maybe we should remove that part of PR checks?

### Additional Info

The action is from here: https://github.com/mtfoley/pr-compliance-action/

**Comment by seriouslysean** [comment]
I did interactively rebase in my PR to follow suit, but GitHub aggressively caches individual commits, lol. I can take a look at this one, too.
