### ISSUE TITLE
🐛 Bug: /ad page should have a <title>

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [philly-js-club/philly-js-club-website#17]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/philly-js-club/philly-js-club-website-remix/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

All pages should have a unique title. https://www.w3.org/WAI/WCAG21/Understanding/page-titled.html

### Actual

https://phillyjs.com/ad?month=april&year=2023 doesn't! Let's add one in based on the provided month & year.

### Additional Info

https://github.com/philly-js-club/philly-js-club-website/blob/09740eb5304452a5b6178dcce50cd0a3eeaa50ce/app/routes/ad.tsx is the page's source.

**Comment by RNR1** [comment]
I can take this; @JoshuaKGoldberg can you assign me? or should I just submit a PR?
