### ISSUE TITLE
🚀 Feature: Store constant values in a file for reuse

### ISSUE THREAD

**Issue by RNR1** [philly-js-club/philly-js-club-website#19]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/philly-js-club/philly-js-club-website-remix/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Currently, no data file contains the fundamental constant values repeated across the website.
The most concerning example is the site title (Philly JS Club) which is currently repeated for every page title and will require a global replacement in case of future changes (not that I believe it should be changed ;)).

It will be handy to have some constants repeated across the website stored somewhere; We might even benefit from some utility functions for common cases like constructing the site title.

### Additional Info

It would be neat to have something like:
```ts
import site from 'config/site';

export const meta: V2_MetaFunction = () => {
  return [{ title: `Some Page | ${site.title}` }];
}
```

Or even:
```ts
import { constructSiteTitle } from 'utils/site';

export const meta: V2_MetaFunction = () => {
  return [{ title: constructSiteTitle("Some page") }];
}
```

I'd be glad to hear your thoughts, it's the most raw idea and I expect some brainstorming around it.

**Comment by JoshuaKGoldberg** [comment]
Seems reasonable. What constants are you thinking of? Site title, ...?

@tjwds and I were talking about how it'd be nice to have documented starting values for the club's description and other common marketing text...

**Comment by RNR1** [comment]
Site:
- title
- description
- baseURL

Region:
- locale
- timeZone

As a side note, I also see some potential data that lives on route components and better move to the data directory:
- `about.tsx` - team -> data/team.json

**Comment by JoshuaKGoldberg** [comment]
@allcontributors add @RNR1 for code

**Comment by JoshuaKGoldberg** [comment]
aha it works!
