### ISSUE TITLE
🛠 Tooling: add package-lock to gitignore

### ISSUE THREAD

**Issue by tjwds** [philly-js-club/philly-js-club-website#42]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/philly-js-club/philly-js-club-website-remix/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Since we use pnpm in our tooling, but it's totally reasonable to expect that other folks might use npm out of habit when getting started with development on the site, we could put the package-lock in gitignore to avoid any accidental commits of a lockfile.

**Comment by tungbq** [comment]
Hi, do you need help. May I pick up this task?
