### ISSUE TITLE
🚀 Feature: Highlight Active Footer Navigation

### ISSUE THREAD

**Issue by codylewis** [philly-js-club/philly-js-club-website#58]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/philly-js-club/philly-js-club-website-remix/issues?q=is%3Aissue) and found none that matched my issue.

## User story

As a user, I want the site navigation to communicate where I am in the site.

## Acceptance criteria

- Links in the site footer should the color white when the user is on that page
    - As of creating this issue this applies to:
        - About
        - Code of Conduct
        - Events
        - Sponsors
        - Join Us

**Comment by RNR1** [comment]
In addition to that, we currently use a simple anchor tag for the navigation links, which causes a full page load for every click. 

We should use the NavLink component, which will also contain the "active" class to indicate which nav item is currently active

**Comment by tjwds** [comment]
So… it turns out the ~annoying~ bespoke deployment situation I've set up doesn't play nicely with `NavLink`.  We'll have to do something else here!
