### ISSUE TITLE
🐛 Bug: Ad page doesn't seem to work in production

### ISSUE THREAD

**Issue by chasenstark** [philly-js-club/philly-js-club-website#61]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/philly-js-club/philly-js-club-website-remix/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

I expected that https://phillyjs.com/ad?month=july&year=2023 would show the Ad page.

### Actual

I got `nope (month)`.

![image](https://github.com/philly-js-club/philly-js-club-website/assets/40804965/db3c618c-7e6a-4576-91d7-13fddac11e8e)

### Additional Info

This works locally, not sure why it's not working in production?

**Comment by RNR1** [comment]
Probably related to the CD pipeline; maybe @tjwds or @JoshuaKGoldberg will know better

**Comment by JoshuaKGoldberg** [comment]
Maybe this is a static site generation thing? That the site is being deployed as static pages, but this page inherently tries to be server-rendered based on params?
