### ISSUE TITLE
🚀 Feature: Use fancy new CSS to make layouts & typography more responsive

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [philly-js-club/philly-js-club-website#7]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/philly-js-club-site/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

I was at React Miami recently, wherein @una gave an awesome talk about all sorts of newer/upcoming CSS features. One of the takeways I came away with is that instead of using hardcoded font sizes at certain breakpoints, we could make font sizing much more dynamic (e.g. a percentage of viewport height/width, with max and/or minimum values). This would use CSS features like `clamp`, `minmax`, etc.

https://www.youtube.com/live/mPPZ-NUnR-4?feature=share&t=1057

I haven't had the time to really dig in and revamp the site - but it would be great if someone else could! 😄 

### Additional Info

#4 is definitely a culprit of my not knowing CSS things as powerfully as I'd wish. 😄

**Comment by chethtrayen** [comment]
Hey, I am new to open-source contributions. I updated the typography with clamps. Is it ok if I can create a PR to get some thoughts on it?

**Comment by JoshuaKGoldberg** [comment]
@chethtrayen yes please, that'd be great! 🙌 

...and welcome to open source!!

**Comment by chethtrayen** [comment]
Thanks, @JoshuaKGoldberg. I am trying to push up my local branch but got this error: 
```
ERROR: Permission to philly-js-club/philly-js-club-website.git denied to chethtrayen.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by JoshuaKGoldberg** [comment]
Yup, you'll have to make a "fork" of the repository. See https://github.com/philly-js-club/philly-js-club-website/blob/main/.github/DEVELOPMENT.md.

For future questions you can reach out to me on the PhillyJS Slack 🙂 happy to help!
