### ISSUE TITLE
🚀 Feature: Upgrade to the latest greatest awesome Remix v2 version

### ISSUE THREAD

**Issue by brophdawg11** [philly-js-club/philly-js-club-website#74]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/philly-js-club/philly-js-club-website-remix/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Run on remix v2!

https://twitter.com/remix_run/status/1702749787102085593

**Comment by JoshuaKGoldberg** [comment]
aight I guess
