### ISSUE TITLE
🛠 Tooling: End-to-end tests take multiple minutes in CI to install Playwright

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [philly-js-club/philly-js-club-website#8]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/philly-js-club-site/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

[Example CI run](https://github.com/philly-js-club/philly-js-club-website-remix/actions/runs/4821274724/jobs/8586932732?pr=4): we're seeing _Install Playwright Browsers_ taking upwards of 5 minutes to run in CI (!). Other tasks tend to take less than a minute! 

This is because the Playwright CI job has to download all(?)/most(?) of Playwright and browsers that it can run on (?). Or something like that.

We should figure out if there's a faster way to do things. Perhaps there's a Docker image or something where we can have Playwright pre-installed...?

### Additional Info

This definitely impacts other repos I've worked on (e.g. https://github.com/dylans/halfstackconf-next). So it'd be lovely to get a good fix that works generically (not just for this one repo).

Either the Playwright docs already say how to do this, or we should file/find an issue asking for an explanation!

**Comment by seriouslysean** [comment]
I wonder if it would be better to specify a singular browser deps, something like `npx playwright install-deps chromium`? They also have a prebuilt image which might be a good candidate, https://playwright.dev/docs/ci#docker.

**Comment by RNR1** [comment]
There's an open issue, and someone mentioned this solution. If it's something you didn't try yet, I can check if this solution improves the running time.
https://github.com/microsoft/playwright/issues/14434#issuecomment-1381806105
