### ISSUE TITLE
🛠 Tooling: use Remix prerender feature 

### ISSUE THREAD

**Issue by tjwds** [philly-js-club/philly-js-club-website#96]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/philly-js-club/philly-js-club-website-remix/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Right now, we're doing something a little silly to create static assets for this site:  we [use wget](https://github.com/philly-js-club/philly-js-club-website/blob/main/.github/workflows/pages.yml#L43) and crawl the site, then stick those assets in a separate repo.  This workflow can now use the new `prerender` feature in Remix instead:  https://github.com/remix-run/react-router/pull/11539

**Comment by brophdawg11** [comment]
FWIW, the `prerender` feature isn't released anywhere official yet so this issue probably has to chill for a bit.  Hopefully soon!

**Comment by tjwds** [comment]
@brophdawg11 I'm totally happy to use an experimental preview if one becomes available! :-)

**Comment by brophdawg11** [comment]
lol this isn’t even experimental territory yet.  This is like pre-alpha of an eventual react router v7 (which is what remix v3 is becoming - pay attention to react conf next week).  

There _is_ something that can be used and I’d get a kick out of the Philly JS site being the first one to use this in production….so maybe I’ll take a stab at it.  The steps to upgrade are not yet documented and exist only in our heads haha

**Comment by JoshuaKGoldberg** [comment]
YYYYYYYAAAAAAASSSSSSSS thank you @brophdawg11!! 🙌  

I also love the idea of us being an early alpha tester kind of project to see how this goes. Marking as `accepting prs`. Let's see what happens!
